language: ruby

dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libsdl2-dev libsdl2-ttf-dev libpango1.0-dev \
                         libopenal-dev libsndfile-dev libmpg123-dev \
