language: ruby

dist: trusty
sudo: requried
compiler: gcc

# Linux dependencies
# This is mostly for Gosu (see https://github.com/gosu/gosu/blob/master/.travis.yml)
# Copied blatantly from https://github.com/gosu/gosu/wiki/Getting-Started-on-Linux
addons:
  apt:
    packages:
      - libsdl2-dev
      - libgl1-mesa-dev
      - libfontconfig1-dev
      - libopenal-dev
      - libsndfile1-dev
      - libmpg123-dev
      - freeglut3-dev
      # For Ruby
      - ruby-dev
      - rake
      # For C++
      - cmake
